import type { Metadata } from 'next';
import { Public_Sans } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';
import { cn } from '@/lib/utils';

const publicSans = Public_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('xl:grid xl:grid-cols-[1fr_4fr] ', publicSans.className)}
      >
        {children}
        <Footer className="xl:order-1" />
      </body>
    </html>
  );
}
